# fly.toml file generated for protohackers-solved on 2023-02-14T10:50:31+09:00

app = "protohackers-solved"
kill_signal = "SIGTERM"
kill_timeout = 5
processes = []

[env]

[experimental]
allowed_public_ports = []
auto_rollback = true

[[services]]
internal_port = 5001
protocol = "tcp"

[[services.port]]
handlers = []
port = "5001"

[[services.tcp_checks]]
grace_period = "1s"
interval = "15s"
restart_limit = 0
timeout = "2s"

[[services]]
internal_port = 5002
protocol = "tcp"

[[services.port]]
handlers = []
port = "5002"

[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"